sla_openldap_proxy:
  image: sla_openldap_proxy:latest
  container_name: sla_openldap_proxy
  ports:
    - '389:389'
    - "636:636"
  volumes:
    - shared_data:/root/openldap_proxy/data
  env_file: ./sla_openldap_proxy.env
  command: bash -l -c "cd /root/openldap_proxy && /usr/sbin/slapd -h 'ldap:/// ldapi:/// ldaps:///' -g ldap -u ldap -d 2"

