sla_openldap_proxy:
  image: "${DTR}/${ORG}/sla-openldap-proxy:${RELEASE}"
  # image: sla_openldap_proxy:latest
  container_name: sla_openldap_proxy
  restart: always
  hostname: ${HOSTNAME}
  ports:
    - "389:389"
    - "636:636"
  volumes:
    - open-ldap-proxy-data:/root/openldap_proxy/data
  env_file: ./sla_openldap_proxy.env
  environment:
    - "DOCKER_HOST_FQDN=${HOSTNAME}"
    - "DOCKER_HOST_MAC=${MAC_ADDRESS}"
  command: bash -l -c "cd /root/openldap_proxy && exec /usr/sbin/slapd -h 'ldap:/// ldapi:/// ldaps:///' -g ldap -u ldap -d 256"

